# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          Username: ${{ secrets.DOCKERHUB_USERNAME }}
          Password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          tags: arahk/reminder:1.0-dev
          file: ./Arahk.Reminder.WebApi/Dockerfile
          context: ./Arahk.Reminder.WebApi
          push: true
          
          
